codecov:
  require_ci_to_pass: yes  # Only allow uploads from successful CI runs.
  token: "${CODECOV_TOKEN}"  # Environment variable to securely provide the Codecov token.

comment:
  layout: "header, diff, flags, files"  # Customize Codecov comments on PRs.
  behavior: default  # Post a comment on every update.
  require_changes: true  # Post a comment only when coverage changes.

coverage:
  precision: 2  # Number of decimal places in coverage percentages.
  round: down  # Round coverage values down.
  range: "80...100"  # Define the coverage range for visual indicators.
  status:
    project:
      default:
        target: 85  # Minimum required coverage for the project.
        threshold: 1  # Allowed deviation from the target percentage.
    patch:
      default:
        target: 85  # Minimum coverage required for changed code in a PR.
        threshold: 1

fixes:
  - "saikidesu/::"  # Remove the 'saikidesu/' prefix from file paths.

flags:
  unittests:
    paths:
      - "tests/unit"  # Coverage for unit tests.
  integration:
    paths:
      - "tests/integration"  # Coverage for integration tests.

ignore:
  - "test/*"  # Exclude test files from coverage.
  - "**/__mocks__/*"  # Exclude mock files.

notifications:
  slack:  # Optional: Configure Slack notifications.
    webhook_url: "${SLACK_WEBHOOK_URL}"  # Provide the webhook via environment variable.
    coverage_decrease: 5  # Notify if coverage decreases by this percentage or more.

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes  # Enable more detailed branch detection.

env_vars:
  - "CI=true"  # Ensure CI environment variables are correctly set for Codecov.

ci:
  - "github-actions"  # Specify the CI provider (adjust as needed).

max_report_age: 7  # Maximum report age (in days).
