name: AniList readme workflow
on:
  schedule:
    - cron: "0 * * * *"
#  push:
#    branches: 
#      - master 
  workflow_dispatch:

jobs:
  update-readme-codecov-and-artifact:
    name: Update README, upload to CodeCov, and store artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@v1.4.2
        with:
          user_id: 5533926
      
      - name: Create dummy coverage report
        run: |
          echo '<?xml version="1.0" ?>
          <coverage version="1">
            <file path="dummy.py">
              <line number="1" hits="1"/>
            </file>
          </coverage>' > coverage.xml
      
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
        #  name: mra1k3r0
        #  override_branch: master
          override_commit: ${{ github.sha }}
          override_build: ${{ github.run_id }}
          override_pr: ${{ github.event.pull_request.number }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 5
