name: AniList readme workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-and-codecov:
    name: Update README and upload to CodeCov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@v1.4.2
        with:
          user_id: 5533926
      
      - name: Create dummy coverage report
        run: |
          echo '<?xml version="1.0" ?>
          <coverage version="1">
            <file path="dummy.py">
              <line number="1" hits="1"/>
            </file>
          </coverage>' > coverage.xml
      
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
