name: AniList readme workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-anilist:
    name: Update this repo's README with latest AniList activites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@v1.4.2
        with:
          user_id: 5533926
      
      # Add CodeCov step
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          fail_ci_if_error: true 
          verbose: true 
